---
####################################################################
# Example :  Global Active Device Pair (GAD) Facts Playbook
####################################################################
- name: GAD Facts
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"
  tasks:
    ############################################################################
    # Task Name : Get all GAD pairs for a copy group name
    # Note: The following output properties are not included in this task output
    #       because retrieving them requires additional REST API calls:
    #       primary_virtual_serial_number, primary_virtual_volume_id,
    #       primary_vsm_resource_group_name, secondary_virtual_serial_number,
    #       secondary_virtual_volume_id, secondary_vsm_resource_group_name
    #       To retrieve these properties, the user must specify both
    #       copy_pair_name and copy_group_name.
    ############################################################################
    - name: Get all GAD pairs for a copy group name
      hitachivantara.vspone_block.vsp.hv_gad_facts:
        secondary_connection_info: "{{ secondary_connection_info }}"
        connection_info: "{{ connection_info }}"
        spec:
          copy_group_name: "copy_group_name_1"

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ###########################################################################
    # Task Name : Get GAD pair by copy group name and copy pair name
    # Note: The following output properties are included in this task output
    #       since one GAD pair is involved, although retrieving them requires
    #       additional REST API calls:
    #       primary_virtual_serial_number, primary_virtual_volume_id,
    #       primary_vsm_resource_group_name, secondary_virtual_serial_number,
    #       secondary_virtual_volume_id, secondary_vsm_resource_group_name
    ############################################################################
    - name: Get GAD pair by copy group name and copy pair name
      hitachivantara.vspone_block.vsp.hv_gad_facts:
        secondary_connection_info: "{{ secondary_connection_info }}"
        connection_info: "{{ connection_info }}"
        spec:
          copy_group_name: "copy_group_name_1"
          copy_pair_name: "copy_pair_name_1"

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get GAD pair using secondary volume Id
    ####################################################################
    - name: Get GAD pair using secondary volume Id
      hitachivantara.vspone_block.vsp.hv_gad_facts:
        secondary_connection_info: "{{ secondary_connection_info }}"
        connection_info: "{{ connection_info }}"
        spec:
          secondary_volume_id: 222
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get GAD pair using primary volume Id
    ####################################################################
    - name: Get GAD pair using only primary volume Id
      hitachivantara.vspone_block.vsp.hv_gad_facts:
        secondary_connection_info: "{{ secondary_connection_info }}"
        connection_info: "{{ connection_info }}"
        spec:
          primary_volume_id: 111
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get all GAD pairs from all copy groups
    ####################################################################
    - name: Get all GAD pairs from all copy groups
      hitachivantara.vspone_block.vsp.hv_gad_facts:
        secondary_connection_info: "{{ secondary_connection_info }}"
        connection_info: "{{ connection_info }}"
        spec:
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
