---
####################################################################
# Example : Snapshot Family Facts playbook
####################################################################

- name: Snapshot Family Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task 1 : Get snapshot family facts by ldev_id
    ####################################################################
    - name: Get snapshot family facts by ldev_id
      hitachivantara.vspone_block.vsp.hv_snapshot_family_facts:
        connection_info: "{{ connection_info }}"
        spec:
          ldev_id: 105
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
