---
######################################################################################
# Example :Snapshot group Pair Module playbook
######################################################################################

- name: Snapshot group Pair Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ######################################################################################
    # Task Name : Split the snapshot pairs using group name
    ######################################################################################
    - name: Split the snapshot pairs using group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "split"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Restore the snapshot pairs using group name
    ######################################################################################
    - name: Restore the snapshot pairs using group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "restore"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Restore the snapshot pairs using group name and auto split
    ######################################################################################
    - name: Restore the snapshot pairs using group name and auto split
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "restore"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
          auto_split: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Resync the snapshot pairs using group name
    ######################################################################################
    - name: Resync the snapshot pairs using group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "sync"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Delete the snapshot pairs using group name
    ######################################################################################
    - name: Delete the snapshot pairs using group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "absent"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Set retention period of snapshots using group name
    ######################################################################################
    - name: Set retention period of snapshots using group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "split"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
          retention_period: 120
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Clone the snapshot pairs using group name
    ######################################################################################
    - name: Clone the snapshot pairs using group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "clone"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
          copy_speed: "SLOW"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Create or convert a snapshot pair to vclone by snapshot group name
    ######################################################################################
    - name: Create or convert a snapshot pair to vclone by snapshot group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          snapshot_group_name: "rd_vclone_ss_grp_6924"
          operation_type: "vclone"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Restore snapshot group from vclone
    # Before performing this operation, you must first create the Thin Image Advanced
    # pair by using volumes that have the vClone attribute.
    ######################################################################################
    - name: Restore snapshot group from vclone
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          snapshot_group_name: "rd_vclone_ss_grp_6924"
          operation_type: "restore"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################################################
    # Task Name : Restore the snapshot pairs using group name and wait for the final state of all snapshots
    # This is applicable for SPLIT, RESTORE, and SYNC operations.
    #####################################################################################################
    - name: Restore the snapshot pairs using group name and wait for the final state of all snapshots
      hitachivantara.vspone_block.vsp.hv_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: "restore"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
          wait_for_final_state: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
