---
####################################################################
# Example :  Storage Pool Facts Playbook
####################################################################
- name: Storage Pool Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get all storage pools
    ####################################################################
    - name: Get all storage pools
      hitachivantara.vspone_block.vsp.hv_storagepool_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get one storage pool
    ####################################################################
    - name: Get one storage pool
      hitachivantara.vspone_block.vsp.hv_storagepool_facts:
        connection_info: "{{ connection_info }}"
        spec:
          pool_id: 15
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get one storage pool using pool name
    ####################################################################
    - name: Get one storage pool using pool name
      hitachivantara.vspone_block.vsp.hv_storagepool_facts:
        connection_info: "{{ connection_info }}"
        spec:
          pool_name: "PoolName1"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
    ####################################################################
    # Task Name : Get all mainframe storage pools
    ####################################################################
    - name: Get all mainframe storage pools
      hitachivantara.vspone_block.vsp.hv_storagepool_facts:
        connection_info: "{{ connection_info }}"
        spec:
          is_mainframe: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get all mainframe storage pools with extended info
    ####################################################################
    - name: Get all mainframe storage pools with extended info
      hitachivantara.vspone_block.vsp.hv_storagepool_facts:
        connection_info: "{{ connection_info }}"
        spec:
          include_details: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #############################################################################################
    # Task Name : Get all mainframe storage pools with cache info for VSP 5XXX series storage
    #############################################################################################
    - name: Get all mainframe storage pools with cache info
      hitachivantara.vspone_block.vsp.hv_storagepool_facts:
        connection_info: "{{ connection_info }}"
        spec:
          include_cache_info: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
