---
####################################################################
# Example : Vclone Parent Volume Facts playbook
####################################################################

- name: Vclone Parent Volume Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get all parent volume IDs of vClone volumes
    ####################################################################
    - name: Get all parent volume IDs of vClone volumes
      hitachivantara.vspone_block.vsp.hv_vclone_parent_volume_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 1 : Get parent volume ID of a specific vClone volume
    ####################################################################
    - name: Get parent volume ID of a specific vClone volume
      hitachivantara.vspone_block.vsp.hv_vclone_parent_volume_facts:
        connection_info: "{{ connection_info }}"
        spec:
          vclone_volume_id: 105
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
