---
####################################################################
# Example : VSP One Snapshot Group Playbook
####################################################################
- name: VSP One Snapshot Group Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ######################################################################################
    # Task Name : Get snapshot group with snapshot pairs by snapshot_group_name
    #######################################################################################
    - name: Get snapshot group with snapshot pairs by snapshot_group_name
      hitachivantara.vspone_block.vsp.hv_vsp_one_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: present
        spec:
          snapshot_group_name: "Thin-AnsibleAuto101802"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################################
    # Task Name : Delete a snapshot group by snapshot_group_name
    ######################################################################################
    - name: Delete snapshot group by snapshot_group_name
      hitachivantara.vspone_block.vsp.hv_vsp_one_snapshot_group:
        connection_info: "{{ connection_info }}"
        state: absent
        spec:
          snapshot_group_name: "Thin-AnsibleAuto101802"

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
