---
####################################################################
# Example : Audit Log Setting Update Playbook
####################################################################
- name: Update Audit Log Settings
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Create Audit Log File on Storage System and Download it
    ####################################################################
    - name: Create and download audit log file
      hitachivantara.vspone_block.sds_block.hv_sds_block_audit_log_setting:
        state: download_audit_log
        connection_info: "{{ connection_info }}"
        spec:
          audit_log_file_location: "/tmp/audit_logs"
          refresh: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Download Audit Log File to the specified location
    ####################################################################
    - name: Download audit log file to /tmp/audit_logs
      hitachivantara.vspone_block.sds_block.hv_sds_block_audit_log_setting:
        state: download_audit_log
        connection_info: "{{ connection_info }}"
        spec:
          audit_log_file_location: "/tmp/audit_logs"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Update Audit Log Settings
    ####################################################################
    - name: Configure audit log settings with syslog forwarding
      hitachivantara.vspone_block.sds_block.hv_sds_block_audit_log_setting:
        state: present
        connection_info: "{{ connection_info }}"
        spec:
          syslog_forwarding_setting:
            location_name: "datacenter1"
            syslog_servers:
              - index: 2
                is_enabled: false
                server_name: "backup2-syslog.example.com"
                port: 514
                transport_protocol: "UDP"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
