---
####################################################################
# Example : Remote Path Group Facts Playbook
####################################################################
- name: Remote Path Group Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
  ################################################################################################
  # Task Name : Get all remote path groups
  ################################################################################################
    - name: Get all remote path groups
      hitachivantara.vspone_block.sds_block.hv_sds_block_remote_path_group_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ################################################################################################
    # Task Name : Get remote path group by id
    ################################################################################################
    - name: Get remote path group by id
      hitachivantara.vspone_block.sds_block.hv_sds_block_remote_path_group_facts:
        connection_info: "{{ connection_info }}"
        spec:
          id: "20be7610-9e5e-4713-bff2-e9d993d1f6d4"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ################################################################################################
    # Task Name : Get remote path groups filtered by other properties
    ################################################################################################
    - name: Get remote path groups filtered by other properties
      hitachivantara.vspone_block.sds_block.hv_sds_block_remote_path_group_facts:
        connection_info: "{{ connection_info }}"
        spec:
          local_storage_controller_id: "3c65e322-ac62-4966-9489-072dbccdf430"
          remote_serial: "810045"
          remote_storage_system_type: "M8"
          path_group_id: 15
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
