---
####################################################################
# Example : SDSB Session Playbook
####################################################################
- name: SDSB Session Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
  ####################################################################
  # Task Name : Create a session
  ####################################################################
    - name: Create a session
      hitachivantara.vspone_block.sds_block.hv_sds_block_session:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #######################################################################
    # Task Name : Create a session with a maximum idle time of 200 seconds
    ######################################################################
    - name: Create a session with a maximum idle time of 200 seconds
      hitachivantara.vspone_block.sds_block.hv_sds_block_session:
        connection_info: "{{ connection_info }}"
        spec:
          alive_time: 200
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Delete a session
    ####################################################################
    - name: Delete a session
      hitachivantara.vspone_block.sds_block.hv_sds_block_session:
        connection_info: "{{ connection_info }}"
        state: "absent"
        spec:
          id: "63ea8269-e6ff-4d24-9e01-3911f69ff905"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
