---
####################################################################
# Example : User Group Facts Playbook
####################################################################
- name: User Group Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
  #############################################################################
  # Task Name : Get all user groups
  #############################################################################
    - name: Get all user groups
      hitachivantara.vspone_block.sds_block.hv_sds_block_user_group_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get a user group by ID
    ####################################################################
    - name: Get a user group by ID
      hitachivantara.vspone_block.sds_block.hv_sds_block_user_group_facts:
        connection_info: "{{ connection_info }}"
        spec:
          id: "ServiceAdministrators"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get user groups by VPS ID
    ####################################################################
    - name: Get user groups by VPS ID
      hitachivantara.vspone_block.sds_block.hv_sds_block_user_group_facts:
        connection_info: "{{ connection_info }}"
        spec:
          vps_id: "2a843522-a819-47ab-a208-69d190809604"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get user groups by VPS name
    ####################################################################
    - name: Get user groups by VPS name
      hitachivantara.vspone_block.sds_block.hv_sds_block_user_group_facts:
        connection_info: "{{ connection_info }}"
        spec:
          vps_name: "RKD_VPS_02"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
