---
####################################################################
# Example : SDSB Session Facts Playbook
####################################################################
- name: SDSB Session Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
  ####################################################################
  # Task Name : Get all Sessions
  ####################################################################
    - name: Get all Sessions
      hitachivantara.vspone_block.sds_block.hv_sds_block_session_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get Session by ID
    ####################################################################
    - name: Get Session by ID
      hitachivantara.vspone_block.sds_block.hv_sds_block_session_facts:
        connection_info: "{{ connection_info }}"
        spec:
          id: "0139f4ee-bcca-4772-a09a-c5bf82437755"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get Session by other properties
    ####################################################################
    - name: Get Sessions by other properties
      hitachivantara.vspone_block.sds_block.hv_sds_block_session_facts:
        connection_info: "{{ connection_info }}"
        spec:
          vps_id: "system"
          user_id: "admin"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
