---
####################################################################
# Example :  Login message management playbook
####################################################################
- name: SDS Block login message management playbook
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Update login message in GUI and CLI banner
    ####################################################################
    - name: Update login message in GUI and CLI banner
      hitachivantara.vspone_block.sds_block.hv_sds_block_login_message:
        connection_info: "{{ connection_info }}"
        state: present
        spec:
          login_message: "login messagee"
      register: result

    - name: Display current login message
      ansible.builtin.debug:
        var: result
