---
####################################################################
# Example : Spare Node Playbook
####################################################################
- name: Spare Node Configuration
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ################################################################################################
    # Task Name : Retrieve all spare node information
    ################################################################################################
    - name: Retrieve all spare node information
      hitachivantara.vspone_block.sds_block.hv_sds_block_spare_node_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ###############################################################################################
    # Task Name : Retrieve specific spare node information by ID
    ###############################################################################################
    - name: Retrieve specific spare node information by ID
      hitachivantara.vspone_block.sds_block.hv_sds_block_spare_node_facts:
        connection_info: "{{ connection_info }}"
        spec:
          id: "spare-node-001"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
